import Head from "next/head";

export default function TurbinAnginEfisiensi() {
  return (
    <>
      <Head>
        <title>Turbin Angin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Wind-Turbine.svg" />
      </Head>
      <div className="min-h-screen">
        <h2>aku Efisiensi angin</h2>
      </div>
    </>
  );
}
