import Head from "next/head";
import { useState } from "react";
import { DownloadButton } from "../../components/button";
import { DownloadModal } from "@/components/modal";

export default function TurbinAngin() {
  const [open, setOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Turbin Angin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Wind-Turbine.svg" />
      </Head>
      <div className="min-h-screen">
        <DownloadButton onClick={() => setOpen(true)} />
        <DownloadModal
          modalTitle="Turbin Angin"
          open={open}
          onClose={() => setOpen(false)}
        />
        <h2>aku Turbin Angin</h2>
      </div>
    </>
  );
}
