import Head from "next/head";
import Image from "next/image";
import { useState, useCallback } from "react";

import { format, set } from "date-fns";

import { ErrorSnackbar } from "@/components/snackbars";
import { useErrorSnackbar } from "@/hooks/snackbars.hooks";

import { Skeleton, Tooltip } from "@mui/material";
// import Tooltip from "@mui/material";
import { DatePicker } from "@mui/x-date-pickers";

import { useQuery, useQueries } from "@tanstack/react-query";
import axios from "axios";

import { EfficiencyChart } from "@/components/charts";

import { OutdoorSolarEfficiencyData } from "@/types/types";

import terbaru from "@/dummies/surya/ac/terbaru.json";
// import efficiencyDummy from "@/dummies/surya/ac/efisiensi.json";
import efficiencyDummy from "@/dummies/surya/ac/generate.json";

const tooltipTitle = (
  <>
    <p className="text-sm">
      Efisiensi daya dihitung dengan membagi{" "}
      <b>daya yang dihasilkan oleh panel surya</b> dengan{" "}
      <b>daya yang diterima oleh panel surya dari matahari</b>.
    </p>
  </>
);

export default function PanelSuryaEfisiensi() {
  const { snackbarOpen, snackbarHandler } = useErrorSnackbar();

  const [dailyDate, setDailyDate] = useState<Date | null>(
    new Date("2023-04-12T23:55:00")
  );

  const changeDate = useCallback((newDate: Date | null) => {
    setDailyDate(newDate);
  }, []);

  // const outdoorSolar = useQuery({
  //   queryKey: ["realData", "outdoor", "solar_power"],
  //   queryFn: async () => {
  //     const res = await axios.get(
  //       `http://10.46.10.128:3001/site/outdoor/solar_power
  //       `
  //     );
  //     // console.log(res.data);
  //     setDailyDate(new Date(res.data.data.lastUpdate as string));
  //     return res.data.data.lastUpdate as string;
  //   },
  //   onError: () => snackbarHandler.open(),
  //   // staleTime: Infinity,
  //   // cacheTime: Infinity,
  //   // select: (data: RealData[]) => data[4],
  // });
  // // // outdoorSolar.isSuccess && setDailyDate(new Date(outdoorSolar.data as string));

  // const efficiencyData = useQuery({
  //   queryKey: [
  //     "efisiensi",
  //     "solar",
  //     { tanggal: format(dailyDate as Date, "yyyy-MM-dd") },
  //   ],
  //   queryFn: async () => {
  //     const res = await axios.get(
  //       `/api/solar/paralel?tanggal=${format(dailyDate as Date, "yyyy-MM-dd")}`
  //     );
  //     return res.data as OutdoorSolarEfficiencyData[];
  //   },
  //   initialData: efficiencyDummy,
  // });

  // const [outdoorSolar, efficiencyData] = useQueries({
  //   queries: [
  //     {
  //       queryKey: ["realData", "outdoor", "solar_power"],
  //       queryFn: async () => {
  //         const res = await axios.get(
  //           `http://10.46.10.128:3001/site/outdoor/solar_power
  //             `
  //         );
  //         // console.log(res.data);
  //         setDailyDate(new Date(res.data.data.lastUpdate as string));
  //         return res.data.data.lastUpdate as string;
  //       },
  //       // staleTime: Infinity,
  //       // cacheTime: Infinity,
  //       // select: (data: RealData[]) => data[4],
  //     },
  //     {
  //       queryKey: [
  //         "efisiensi",
  //         "solar",
  //         { tanggal: format(dailyDate as Date, "yyyy-MM-dd") },
  //       ],
  //       queryFn: async () => {
  //         const res = await axios.get(
  //           `http://localhost:3000/api/solar/paralel?tanggal=${format(
  //             dailyDate as Date,
  //             "yyyy-MM-dd"
  //           )}`
  //         );
  //         return res.data as OutdoorSolarEfficiencyData[];
  //       },
  //     },
  //   ],
  // });

  // console.log(outdoorSolar.data);

  return (
    <>
      <Head>
        <title>Panel Surya</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Solar-Panel.svg" />
      </Head>

      <ErrorSnackbar toastOpen={snackbarOpen} toastHandler={snackbarHandler} />

      <div className="pb-8">
        {/* <h2>aku Efisiensi solar</h2> */}
        <section
          id="harian"
          className="mt-2 flex flex-col bg-white shadow-md rounded-3xl"
        >
          <div className="mx-9 my-6">
            <div className="flex flex-row justify-between">
              <div className="flex flex-col gap-2">
                <div className="flex flex-row gap-2 justify-center">
                  <h3 className="text-2xl font-bold">
                    Rasio Daya <span className="text-[#9747FF]">Input</span> vs{" "}
                    <span className="text-[#9747FF]">Output</span>
                  </h3>
                  <Tooltip
                    title={tooltipTitle}
                    placement="right"
                    arrow
                    sx={{ backgroundColor: "white", color: "black" }}
                  >
                    <button>
                      <Image
                        src="/question-mark.svg"
                        alt="question mark"
                        width={18}
                        height={18}
                      />
                    </button>
                  </Tooltip>
                </div>

                <p className="italic bg-[#9747FF] bg-opacity-30 px-2 w-fit rounded font-semibold">
                  Update Terbaru :{" "}
                  <span className="font-bold ">
                    {format(
                      new Date("2023-06-30T23:59:58"),
                      "dd/MM/yyyy HH:mm:ss"
                    )}{" "}
                    WIB
                  </span>
                </p>
                {/* {outdoorSolar.isSuccess && (
                  <p className="italic text-sm">
                    Last updated :{" "}
                    {format(
                      new Date(outdoorSolar.data as string),
                      "dd/MM/yyyy HH:mm:ss"
                    )}{" "}
                    WIB
                  </p>
                )} */}
              </div>

              <DatePicker
                label="Masukkan Tanggal"
                value={dailyDate}
                views={["year", "month", "day"]}
                defaultValue={new Date()}
                onChange={changeDate}
                disableFuture
                format="dd/MM/yyyy"
                className="mr-16"
                // maxDate={new Date(outdoorSolar.data)}
              />

              {/* {outdoorSolar.isSuccess ? (
                <DatePicker
                  label="Masukkan Tanggal"
                  // value={dailyDate}
                  views={["year", "month", "day"]}
                  defaultValue={new Date(outdoorSolar.data)}
                  onChange={changeDate}
                  disableFuture
                  format="dd/MM/yyyy"
                  className="mr-16"
                  maxDate={new Date(outdoorSolar.data)}
                />
              ) : (
                <>
                  <Skeleton variant="rectangular" width={200} height={50} />
                </>
              )} */}
            </div>
            <div className="mt-9 ml-16 mr-2">
              <EfficiencyChart data={efficiencyDummy} />

              {/* {efficiencyData.isSuccess ? (
                <EfficiencyChart
                  data={efficiencyData.data as OutdoorSolarEfficiencyData[]}
                />
              ) : (
                <Skeleton variant="rectangular" width={1100} height={435} />
              )} */}
            </div>
          </div>
        </section>
        {/* <Skeleton variant="rounded" className="mt-4 h-40" />
        <Skeleton variant="rounded" className="mt-4 h-40" /> */}
      </div>
    </>
  );
}
