import Head from "next/head";
import { Skeleton } from "@mui/material";

export default function PanelSuryaEfisiensi() {
  return (
    <>
      <Head>
        <title>Panel Surya</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Solar-Panel.svg" />
      </Head>
      <div className="pb-8">
        {/* <h2>aku Efisiensi solar</h2> */}
        <Skeleton variant="rounded" className="mt-4 h-40" />
        <Skeleton variant="rounded" className="mt-4 h-40" />
      </div>
    </>
  );
}
