import Head from "next/head";

export default function PanelSuryaAC() {
  return (
    <>
      <Head>
        <title>Panel Surya</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen">
        <h2>Aku AC</h2>
      </div>
    </>
  );
}
